project:
  type: website
  output-dir: "docs"

website:
  description: "Outi Sarpila"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Outi Sarpila"
  favicon: profile.jpg
  navbar:
    right:
      - text: About
        file: about.qmd
      - research.qmd
      - publications/index.qmd
      - teaching.qmd
      - data.qmd
      - cv.qmd
      - icon: twitter
        href: https://twitter.com
    background: "#ffeeff"
    search: false
    
format:
  html:
    backgroundcolor: "#ffeeff"
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

