project:
  type: website
  output-dir: "docs"

website:
  description: "Outi Sarpila"
  site-url: https://outisarpila.github.io
  title: "Outi Sarpila"
  favicon: profile.jpg
  navbar:
    #right:
      #- research.qmd
      #- publications/index.qmd
      #- teaching.qmd
      #- data.qmd
      #- cv.qmd
    background: "#ffeeff"
    search: false
    
format:
  html:
    backgroundcolor: "#ffeeff"
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

